<#
  RealmForge Extractor v0.5 - reads your Watcher of Realms account from game memory and
  sends it to the RealmForge site (or saves it as account.json).

  * READ-ONLY: it only reads the memory of the running game (ReadProcessMemory) and never
    writes to it, never touches game files and never talks to the game servers.
  * Network: one HTTPS request to the site address shown in the window, nothing else.
  * Settings: %APPDATA%\RealmForge\config.json (the sync code is encrypted with Windows DPAPI).

  Start it with Run-RealmForge.bat. The game runs as administrator, so reading its memory needs
  the same rights: the script asks for them (UAC) unless started with -NoElevate.

  This file is GENERATED by tools/build.mjs from src/ - edit the sources, not this file.
  Requirements: Windows 10/11, Windows PowerShell 5.1, .NET Framework 4.5+ (all built in).
#>
#Requires -Version 5.1
param([switch]$NoElevate)
$ErrorActionPreference = 'Stop'

# --- administrator rights -----------------------------------------------------------------
$identity = [Security.Principal.WindowsIdentity]::GetCurrent()
$isAdmin = ([Security.Principal.WindowsPrincipal]$identity).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin -and -not $NoElevate) {
  try {
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -WindowStyle Hidden -ArgumentList @(
      '-NoProfile', '-ExecutionPolicy', 'Bypass', '-WindowStyle', 'Hidden', '-File', ('"{0}"' -f $PSCommandPath))
    exit 0
  } catch {
    # The UAC prompt was declined: open the window anyway, it explains what is missing
    # and offers "Restart as administrator" when the game cannot be read.
  }
}

# --- the program (C#, compiled in memory by the built-in .NET Framework compiler) ------------
$source = @'
/*@@CSHARP@@*/
'@

try {
  if (-not ('RealmForge.App' -as [type])) {   # already compiled in this PowerShell session?
    $addType = @{
      TypeDefinition       = $source
      Language             = 'CSharp'
      IgnoreWarnings       = $true
      ReferencedAssemblies = @('System.Windows.Forms', 'System.Drawing', 'System.Security')
    }
    Add-Type @addType
  }
} catch {
  Add-Type -AssemblyName System.Windows.Forms
  [void][System.Windows.Forms.MessageBox]::Show(
    "RealmForge не запустился / could not start:`n`n" + $_.Exception.Message,
    'RealmForge', 'OK', 'Error')
  exit 1
}

[RealmForge.App]::Run($PSCommandPath)
